### ISSUE TITLE
Fehlende Rundung bei einigen Werten

### ISSUE THREAD

**Issue by luconlua** [luconlua/sopra-cloud#1]
Einige Modbusregister liefern mehr Nachkommastellen als eigentlich gemäß Datenpunktliste konfiguriert sind. Das ist abhängig vom Gerätetyp und betrifft nur den Datentyp Float32

**Comment by wtuz** [comment]
Die Werte werden nur abgeschnitten, nicht gerundet?
z.B. ein Float-Wert von 13,38 wird als 13,3 angezeigt.
