### ISSUE TITLE
Anzeige des Status in der cloud  der Niveaumesssonden in der pool control funktioniert nicht mehr

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#100]
@luconlua 
Seit einigen Tagen funktioniert die optische Anzeige im Status der Niveausonden bei der Testanlage 1 nicht mehr, obwohl die Anlage live einwandfrei funktioniert, soll heißen, es wird Wasser bei Bedarf autom. nachgespeist usw. Auch zeigen die Werte im Diagnose Einträge-Register die richtigen Werte an. Die Anzeige in der Cloud bleiben aber grau.
![Anmerkung 2020-08-13 115419](https://user-images.githubusercontent.com/67409030/90137775-5fb81380-dd76-11ea-90c0-4a27392d8cf4.png)
![Anmerkung 2020-08-13 115626](https://user-images.githubusercontent.com/67409030/90137783-6181d700-dd76-11ea-82eb-983a37049ffb.png)
![Anmerkung 2020-08-13 150325](https://user-images.githubusercontent.com/67409030/90137787-63e43100-dd76-11ea-8ebb-06e13f5fa2cb.png)

**Comment by wtuz** [comment]
Das liegt an der Software des Gerätes, hier hat sich mit der Softwareversion 2.0d ein Fehler eingeschlichen...

**Comment by wtuz** [comment]
Korrektur aber Softwareversion V2.0e
