### ISSUE TITLE
sopra pool control - Warnung Zwangseinschaltung max wird in Meldungen nicht angezeigt

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#101]
Fehler ausgelöst am 17.08.2020, 8:34

![image](https://user-images.githubusercontent.com/35223218/90364905-3ee90a00-e065-11ea-9f17-84bea7137a8a.png)

Diese zwei Meldungen (also "Störung Niveau max2" und "Warnung Zwangseinschaltung Max2" werden gleichzeitig gesetzt. 
Hängt es damit zusammen? 

Oder liegt es daran, dass die Meldung Zwangseinschaltung max hier noch vom 31.07.2020 als aktiv steht:
![image](https://user-images.githubusercontent.com/35223218/90365023-79eb3d80-e065-11ea-8e18-258e38a18745.png)

Wenn die Fehler/Warnung gehen schaut es wie folgt aus (am 17.08.2020 um 8:45):
![image](https://user-images.githubusercontent.com/35223218/90365506-288f7e00-e066-11ea-92ed-bf2424f2a1de.png)

**Comment by luconlua** [comment]
ja, es liegt daran, dass die Meldung bereits seit dem 31.07 aktiv ist.
