### ISSUE TITLE
Sicherheitsabfrage vor dem Betätigen der Poolabdeckung

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#103]
@luconlua
@wtuz 
vor der Betätigung der Poolabdeckung (beim Öffnen und beim Schließen) über die sopra pool control, muss eine Sicherheitsabfrage kommen die mit ja / nein zu beantworten ist.
Bei "ja" wird die Bedienung freigeschaltet.
Bei "nein" wird die Bedienung weitergeleitet auf die Frage zwei oder nicht freigeschaltet.

Sicherheitsabfragetexte:
- Ist der Pool von Ihnen einsehbar und frei von Personen, Tieren und Gegenständen? (ja/nein)
wenn "ja" dann zur nächsten Frage.
wenn "nein" dann sperren.
- Ist der Pool ausreichend mit Wasser gefüllt und sind alle Attraktionspumpen ausgeschaltet? (ja/nein)
wenn "ja" dann freischalten.
wenn "nein" dann sperren.

**Comment by wtuz** [comment]
Doppelt mit #64 und #42
