### ISSUE TITLE
Testanlage 1 - soprazon meldet sich nicht an

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#104]
@wtuz 
bei der Testanlage 1 meldet sich die soprazon wieder nicht an

**Comment by wtuz** [comment]
Sind sie Vorort? oder haben Sie Homeoffice?

Was wird im Menü "Setup System" -> Ethernet bei den Statusanzeigen angezeigt?
Blinkt Modbus grün, oder ist die Anzeige aus?

**Comment by sg-sopraAG** [comment]
Modbus hatte nicht geblinkt.
habe die soprazon stromlos geschaltet und wieder aktiviert - dies hatte keinen Erfolg
habe das Neztwerkkabel ausgeklemmt und wieder eingeklemmt - dies hatte dann funktioniert
die soprazon ist wieder online.
Bitte überprüfen Sie diese Störung.

**Comment by wtuz** [comment]
Herr Lucks, können Sie bitte bei der Testanlage 1 den Log des GW auslesen?

**Comment by wtuz** [comment]
@sg-sopraAG  
Welches Netzwerkkabel haben Sie abgezogen? Das von der soprazon ? oder von dem Gateway?
Wie lange haben Sie nach dem stromlos schalten der soprazon gewartet?

**Comment by sg-sopraAG** [comment]
ich hatte die Anlage ca. 15s stromlos.
ich hatte das Netzwerkkabel von der soprazon gezogen.

**Comment by luconlua** [comment]
Leider gibt es Probleme mit dem Logging auf dem Gateway.  Die Log-Dateien enthalten leider keine aktuellen Einträge 
Problem wird gerade analysiert

**Comment by luconlua** [comment]
#109

**Comment by luconlua** [comment]
Logging-Probleme sind gelöst
