### ISSUE TITLE
Meldungen u. Fehlermeldungen-Alarme: unterschiedliche Anzeigenamen bzw. Kachelnamen in den Geräten

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#105]
@wtuz 
kann man da nicht irgendwie besser angleichen?

- soprazon = Meldungen
- pool control = Fehler
- sopra test = Meldungen

![Anmerkung 2020-08-24 101128](https://user-images.githubusercontent.com/67409030/91020608-f7c5c080-e5f2-11ea-9207-ec2bee26750d.png)
![Anmerkung 2020-08-24 101302](https://user-images.githubusercontent.com/67409030/91020611-fa281a80-e5f2-11ea-839d-0dba662ad28c.png)
![Anmerkung 2020-08-24 101426](https://user-images.githubusercontent.com/67409030/91020619-fbf1de00-e5f2-11ea-977b-a77236c2e4aa.png)

**Comment by wtuz** [comment]
Aus meiner Sicht würde das Sinn machen, wenn man bei der pool control das wie folgt ändert:

![image](https://user-images.githubusercontent.com/35223218/91026373-f3050a80-e5fa-11ea-85bd-f8a263d12c6a.png)


Wäre das dann aus ihrer Sicht so i.O. ?

**Comment by sg-sopraAG** [comment]
ja... das wäre so besser.

**Comment by wtuz** [comment]
Änderung enthalten ab Datenpunktliste vom 25.08.2020
