### ISSUE TITLE
Entfeuchtungsanlage UDP Broadcast

### ISSUE THREAD

**Issue by luconlua** [luconlua/sopra-cloud#108]
Die Steuerung antwortet auf ein UDP Broadcast des Gateways wiederum mit einem eigenen Broadcast. Die Antwort muss aber direkt an das Gateway gerichtet werden (siehe EVOQUA Geräte im Bild). Die zufällige Verzögerung bis zu 1 Sekunde für die Antwort bitte rausnehmen.

![image](https://user-images.githubusercontent.com/25524211/91270313-bc54fe80-e778-11ea-8630-d466b175c678.png)

**Comment by JochenHerget** [comment]
Wir können momentan die Source-IP-Adresse nicht mit unserer Steuerung ermitteln.
Dazu benötigen wir die Unterstützung von unserem Hardware-Hersteller.
Das kann jedoch noch einige Wochen dauern.

**Comment by JochenHerget** [comment]
Das Problem mit der "Broadcast-Antwort" wurde am 15.9.20 behoben. Die UNICON-Steuerung antwortet jetzt nur an den Teilnehmer, von dem die Anfrage kam.
