### ISSUE TITLE
Trendanzeige in Detailansicht

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#11]
Achsenbeschriftung nicht korrekt

![image](https://user-images.githubusercontent.com/35223218/86244604-847e7000-bba8-11ea-8179-7bd1abc83f64.png)

**Comment by Hendrik-Mueller** [comment]
Momentan wird der Wert "yAxisNullUnit" falsch aus der WebApi übergeben. @luconlua schaut sich das Problem an.
Es wurde vorerst ein Nullwert in die Übersetzungstabelle eingetragen.
