### ISSUE TITLE
Anzeigeproblem der Geräte

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#112]
@luconlua @wtuz 
heute wird die sopra pool control nicht mehr angezeigt
![Anmerkung 2020-09-10 095314](https://user-images.githubusercontent.com/67409030/92697886-1397c900-f34c-11ea-9d25-a80538c9ba06.png)

**Comment by wtuz** [comment]
Ich vermute dass die sopra pool control neu gestartet werden muss.

Bitte vorher in das Menü Einstellungen -> Netzwerk -> Status gehen und für 3 Minuten mal beobachten ob UDP aufblinkt, bzw. ob Modbus blinkt.

**Comment by sg-sopraAG** [comment]
@wtuz 
@luconlua 
UDP blinkte nicht und Modbus auch nicht. Nach dem Ausschalten des Gateways (2 Min) und wieder Einschalten, war das Gerät immer noch nicht online. Nach dem Stromlosschalten der pool control funktionierte es wieder.

**Comment by luconlua** [comment]
Denke das Problem sollte erledigt sein
