### ISSUE TITLE
wöchentliche E-Mails werden nicht versendet

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#115]
![image](https://user-images.githubusercontent.com/35223218/94650628-5c152780-02f7-11eb-9703-123a542617fc.png)

**Comment by luconlua** [comment]
War Konfigurationsfehler

**Comment by wtuz** [comment]
@luconlua 

Ich habe heute die Tagesmail bekommen mit dem Archiv.
Mir ist aufgefallen, dass die Daten vom 4.11 / 2 Uhr bis 5.11 / 1:59 Uhr sind.

Also prinzipiell ok, schöner wäre aber natürlich, wenn es immer von 0 Uhr starten würde, sodass man einen kompletten Tag hat.

**Comment by luconlua** [comment]
Ok - Export beginnt jetzt um Mitternacht

**Comment by wtuz** [comment]
Heutige E-Mail:

![image](https://user-images.githubusercontent.com/35223218/98332055-3a961280-1ffe-11eb-9910-bca25654be49.png)

Das sind jetzt aber nicht alle Daten vorhanden, an dem IoT-Gateway-Evoqua müssten viel mehr Spalten angezeigt werden
Gestern waren noch einige mehr Spalten vorhanden.

**Comment by luconlua** [comment]
Erste Analyse: Es sind nicht mehr Daten in der Datenbank. Warum ist noch unklar und wird gerade geprüft

**Comment by luconlua** [comment]
Problem: das CSV enthält nur Werte, die sich im Betrachtungszeitraum geändert haben. Wenn also  im Betrachtungszeitraum keine Wertänderung vorliegt (z.B. weil Sollwert konstant), dann fehlen die entsprechenden Spalten.
Verhalten wurde jetzt wie folge geändert: 
1. Es werden immer alle Spalten aufgeführt, auch wenn es für diese keine Werte gibt
2. Die Zeitreihe startet immer mit dem letzten Wert aus dem vorherigen Betrachtungszeitraum (der auch NULL sein kann), so dass die Zeitreihe fortgeschrieben wird, auch wenn es keine Wertänderung im Zeitraum gab
