### ISSUE TITLE
Trend Download

### ISSUE THREAD

**Issue by KleiberW** [luconlua/sopra-cloud#116]
Im Trenddiagramm funktioniert der Download nicht und es erscheint eine Fehlermeldung "Bei der Anfrage ist etwas schief gelaufen. Bitte versuchen Sie es später noch einmal"

**Comment by luconlua** [comment]
Problem ist nachvollziehbar. Der Download wird anscheinend zu groß (vermutlich durch die hohen Abtastraten). Weitere Analyse ist in Arbeit

**Comment by luconlua** [comment]
Download-Zeitraum wurde auf 7 Tage reduziert. Außerdem wird nun ein gezipptes Archiv heruntergeladen .
Auch beim Zeitreihen-Direktversand per E-Mail werden nur noch die letzten 7 Tage betrachtet
