### ISSUE TITLE
sopra-test - Parameter wird angezeigt obwohl OSV = 0 (cloud.sopra.de) 

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#117]
![image](https://user-images.githubusercontent.com/35223218/95044908-f81ca580-06e0-11eb-87d9-b4119de0ade7.png)

das gleiche hier:

![image](https://user-images.githubusercontent.com/35223218/95044992-2d28f800-06e1-11eb-8626-ffb213ba78d7.png)

**Comment by luconlua** [comment]
Fehler ist gefunden und behoben. 
Update Gateway-Software notwendig
