### ISSUE TITLE
Anzeigestörung: Gerätename von Herget , sopraAG Schulungsanlage

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#122]
@wtuz 
@luconlua 
Der Gerätename wird nicht mehr richtig angezeigt, bitte überprüfen Sie die Sache.
Ich werde bis dahin das Gerät nicht abschalten und wieder neu anschließen.
![Störung-Anzeige-Hergetanlage](https://user-images.githubusercontent.com/67409030/98358125-865cb200-2026-11eb-8258-e0c04743dcbb.png)

**Comment by wtuz** [comment]
@sg-sopraAG  @JochenHerget 

Wurde am Mittwoch in der Besprechung bereits von mir erwähnt - Auf die Lüftungssteuerung muss die aktuelle Software aufgespielt werden.
Die wollte Herr Herget uns noch zukommenlassen.

**Comment by luconlua** [comment]
Ist der Punkt noch offen?

**Comment by wtuz** [comment]
ist erledigt

**Comment by JochenHerget** [comment]
Das Problem lag an der Umstellungen der Gerätebezeichnung.
Diese wird nun mittels Modbus übertragen nicht nicht mehr durch einen festen Eintrag in der Excel-Liste.
Mit dem neuen Software-Update V2.3.2 der UNICON-Steuerung ist das Problem behoben.

**Comment by sg-sopraAG** [comment]
Ist erledigt.

Mit freundlichen Grüßen aus Koblenz /
Best regards from Koblenz

[cid:image001.jpg@01D6C3D1.B45AD080]

[cid:image002.jpg@01D6C3D1.B45AD080]

i. A. Stefan Guckert
Dipl.-Ing.(FH)
Technischer Leiter | Systemplanung

Tel.:  +49 (0) 261 98308-12
Fax.: +49 (0) 261 98308-20
E-Mail:  guckert@sopra.de<mailto:guckert@sopra.de>


sopra AG Schwimmbad- und Freizeittechnik | Ferdinand-Nebel-Straße 3 | D-56070 Koblenz
Zentrale: +49 (0) 261 98308-0 | www.sopra.de<outbind://5/www.sopra.de>

Vorstand: Oliver Kasper
Aufsichtsratsvorsitzende: Christine Henne-Zapf
USt-IdNr. DE 186575939
Registergericht Koblenz HRB6925

Die Information in dieser E-Mail ist nur für die Person oder juristische Person, die angeschrieben wurde, bestimmt und kann vertrauliche
und/oder geschützte Daten enthalten. Jegliche Überprüfung, Weitergabe oder sonstige Verwendung durch eine andere als die
angeschriebene Person ist nicht gestattet.
Wenn der Leser dieser Nachricht nicht der vorgesehene Adressat oder dessen Beauftragter ist, bitte umgehend den Absender informieren
und die Nachricht mit allen Anhängen in jeder Form und von jedem Computer löschen.
________________________________________________________________________________________

Mitglied im

[cid:image003.jpg@01D6C3D1.B45AD080]

[cid:image004.jpg@01D6C3D1.B45AD080]
sopra Wellness-Planer



Von: luconlua <notifications@github.com>
Gesendet: Mittwoch, 25. November 2020 16:05
An: luconlua/sopra-cloud <sopra-cloud@noreply.github.com>
Cc: Stefan Guckert <guckert@sopra.de>; Mention <mention@noreply.github.com>
Betreff: Re: [luconlua/sopra-cloud] Anzeigestörung: Gerätename von Herget , sopraAG Schulungsanlage (#122)


Ist der Punkt noch offen?
