### ISSUE TITLE
Update Datenpunktliste vom 07.12

### ISSUE THREAD

**Issue by luconlua** [luconlua/sopra-cloud#129]
Hr. Zacher hat am 07.12. eine neue Version der Datenpunktliste bereitgestellt. Diese muss auf Test- und Live-System installiert werden.

**Comment by luconlua** [comment]
Es gibt noch ein Problem mit Parameter 3252 


0x0001|soprazon.opt.BereitungAus;
0x0002|soprazon.opt.BereitungStandby;
0x0004|soprazon.opt.BereitungAnlauf;
0x0008|soprazon.opt.BereitungAktiv;
0x0010|soprazon.opt.SpülungAktiv;
0x0040|soprazon.opt.AusliternAktiv;
0x0200|soprazon.opt.VorbefüllenAktiv;
0x0800|soprazon.opt.Störung;
**0x1000|soprazon.opt.Wiederanlauf;
0x1000|soprazon.opt.Regeneration**

**Comment by wtuz** [comment]
Datenpunktliste in Teams hochgeladen
