### ISSUE TITLE
Zugriff über Microsoft Edge Browser

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#13]
Zugriff nicht möglich

(Aktuelle Edge Version: 83.0.478.58 (Offizielles Build) (64-Bit)

**Comment by luconlua** [comment]
Konnte es direkt einmal nachstellen. Danach aber nicht mehr
Ursache unklar

**Comment by luconlua** [comment]
Konnte jetzt nicht mehr reproduziert werde. Bitte noch mal testen

**Comment by luconlua** [comment]
Hatte gestern doch noch mal ein Problem. Musste den Service-Worker für testcloud.sopra.de von Hand löschen. Kollidierte mit dem Service-Worker für testcloud.sopra.de/app
