### ISSUE TITLE
Fehlermeldungen: 

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#132]
@luconlua 
Fehlermeldungen werden immer noch angezeigt (s. Foto) obwohl keine mehr anliegen.
![Fehlermeldungen](https://user-images.githubusercontent.com/67409030/104165558-d4f94480-53f9-11eb-9653-e5ed22ece40b.png)

**Comment by sg-sopraAG** [comment]
Hier liegen momentan tatsächlich kar keine Fehler o. Störungen an !?

**Comment by luconlua** [comment]
doppelt  siehe [#133 ](url)
