### ISSUE TITLE
Fehlermeldungen - 2:

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#133]
@luconlua 
Anzahl der Fehlermeldungen stimmen nicht (s. Foto) 
![Fehlermeldungen-2](https://user-images.githubusercontent.com/67409030/104166426-13dbca00-53fb-11eb-928c-ddc4f54d56c2.png)

**Comment by luconlua** [comment]
Können Sie mir die Anlage freigeben? Auch die von  "Hotel schöne Aussicht"

**Comment by sg-sopraAG** [comment]
sind beide für Sie freigegeben.

**Comment by luconlua** [comment]
Die Abweichungen sind nachvollziehbar und treten auch bei diversen anderen Anlagen auf. Allerdings ist die Ursache noch unklar. Habe jetzt die Fehlerzähler erstmal neu initialisiert , so dass die jetzt bei allen Anlagen wieder passen. Werden regelmäßig Plausi-Checks machen und bei Abweichungen der Zähler zeitnah den Fehler weiter analysieren  zu können

**Comment by sg-sopraAG** [comment]
haben Sie auch gesehen, dass der Fehlerzähler nicht wieder auf "0" geht wenn die Ströung beseitigt wurde.

**Comment by luconlua** [comment]
ja, wenn man die Anlage gerade geöffnet hat, fehlt ein Update in den Kacheln, wenn der Fehlerzähler wieder auf "0" gesetzt wird (und vorher ein Fehler aktiv war). Wenn man die Anlage erneut öffnet, passt es aber wieder. Das ist ein weiterer Fehler, der sich aber reproduzieren lässt. Die dauernde Abweichung der Fehlerzähler (auch nach erneuten Öffnen, Anlage trennen und neu verbinden) ist ein anderes Problem

**Comment by luconlua** [comment]
Die dauernde Abweichung der Fehlerzähler ist behoben. Das fehlende Zurücksetzen in der Anzeige, wenn sich der Fehlerzähler auf "0" ändert während man die Anlage geöffnet hat, ist noch offen

**Comment by luconlua** [comment]
Das Ausblenden des Fehlerzählers, wenn keine Störung mehr ansteht funktioniert jetzt auch bei geöffneter Anlage
