### ISSUE TITLE
Fehlermeldung: Löschen eines Benutzers

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#134]
Beim Löschen eines Benutzers tritt dieser Fehlter auf.
![Screenshot 2021-01-18 074250](https://user-images.githubusercontent.com/67409030/104886282-c2d35500-5969-11eb-8201-8dd595891ccc.png)

**Comment by luconlua** [comment]
Fehler hängt mit der Umstellung auf Benutzergruppen zusammen. Benutzer löschen muss diesbezüglich noch angepasst werden
