### ISSUE TITLE
Anzeige im Trenddiagramm: Pumpenaktivität an bzw. aus

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#137]
@luconlua 
@wtuz 
ist es möglich im Trenddiagramm die Filterpumpenaktivität darzustellen?
also Funktion "aus" bzw. "ein"
Hier müsste mann noch die Überwachung von der Durchflussfreigabe beachten.
Diese Funktion wäre für die Diagnostik der Anlage wichtig.

**Comment by luconlua** [comment]
um welche PTID handelt es sich?

**Comment by sg-sopraAG** [comment]
PTID??

**Comment by wtuz** [comment]
@luconlua @sg-sopraAG 
Ich würde eine separate Variable erzeugen, so dass man gleich im Trend sieht, ob die Pumpe in ECO-Drehzahl, Normaldrehzahl, oder Rückspüldrehzahl läuft. 

@luconlua  deswegen auch gestern meinee Frage an Sie, ob man ein Dropdownfeld im Trend anzeigen lassen kann (was ja bereits  geklärt ist)
Die Varaible gibt es mit der neuen Softwareversion der pool control touch, deswegen auch wichtig, dass so bald wie möglich das Gateway OsvScript unterstützt.

**Comment by sg-sopraAG** [comment]
@luconlua @wtuz 
Der Vorschlag von H. Zacher unterstütze ich. Dann wäre noch zu klären, ob man auch darstellen kann, ob die Anlage im Schwimmbadbetrieb oder im Whirplpoolbetrieb sich befindet o. befunden hat.

**Comment by wtuz** [comment]
@sg-sopraAG  habe ich bereits ebenfalls vorgesehen dass das im Trend mitgeloggt wird.

**Comment by wtuz** [comment]
Verfügbar aber Softwareversion pool control V02.02 und 
Datenpunktliste-Version 1.03
