### ISSUE TITLE
Anzahl der Fehlermeldungen (Anzeigen)

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#138]
@luconlua 
die Anzahl der Gesamtfehler mit den einzelnen Fehler pro Geräte stimmen nicht überein
![Anzahl der Fehlermeldungen 2021-03-22 124120](https://user-images.githubusercontent.com/67409030/111985966-9bd20480-8b0d-11eb-9321-34fcd0acc663.png)

**Comment by luconlua** [comment]
Das Gateway war, bevor es beim Kunden installiert wurde, in einer anderen Umgebung online (vermutlich Sopra-Schulungsanlage) und hatte daher bereits Geräte  (mit aktiven Fehlern) zugeordnet. Die Geräte wurden anschließend gelöscht dabei wurde der Fehlerzähler nicht aktualisiert. Ist jetzt behoben

**Comment by luconlua** [comment]
Fehlerbehebung ist noch nicht live geschaltet

**Comment by luconlua** [comment]
Kann auf dem Testsystem getestet werden
