### ISSUE TITLE
Änderungslog Multiselect-Parameter

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#14]
Kann für Mehrfachauswahlfelder der neue/alte Wert als Klartext angezeigt werden?

![image](https://user-images.githubusercontent.com/35223218/86245924-81847f00-bbaa-11ea-8575-8729fa88372a.png)

**Comment by luconlua** [comment]
Es müssen für vorher und nachher alle aktiven Optionen aufgelistet werden

**Comment by luconlua** [comment]
Serverseitige Anpassungen sind erfolgt. 
Anzeige folgender ControlTypessind noch im Client zu implementieren (anstatt Anzeige des Zahlenwertes)
DropDownList
MultiSelect
Switch,
RgbPicker
CommandAndStateGroup,
TextSlider

**Comment by luconlua** [comment]
Einheit bei alt/neu anzeigen, wenn verfügbar

**Comment by wtuz** [comment]
Bei Dropdownlisten mit nur zwei Auswahlmöglichkeiten (Aus/Ein) läuft noch etwas schief:

![image](https://user-images.githubusercontent.com/35223218/90386705-3d2f3e80-e085-11ea-9da3-a934ce3e497d.png)

**Comment by luconlua** [comment]
ist behoben
