### ISSUE TITLE
Funktionalität „Service“-Button 

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#16]
Momentan keine Funktion?

![image](https://user-images.githubusercontent.com/35223218/86246539-72520100-bbab-11ea-91a2-9ce29af4fa0e.png)

**Comment by luconlua** [comment]
Der Service Button wird zukünftig entfallen und durch ein neues Gruppen basiertes Freigabekonzept ersetzt (Umsetzung KW 34/35)

**Comment by luconlua** [comment]
Neues Freigabekonzept ist live, den Button gibt es nicht mehr
