### ISSUE TITLE
Setzen/Schreiben von Datum/Uhrzeit

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#17]
Das Schreiben der Uhrzeit funktioniert nicht korrekt. (Am Gerät werden 2 Std. weniger angezeigt)
Wir haben die Zeit an unserem Gerät überprüft siehe  https://www.unixtimestamp.com/index.php
Der Wert 1588598942 entspricht 2020-05-04 13:29 Uhr.   Nach dem Schreiben über die Cloud wird aber 11:29 Uhr angezeigt.

**Comment by luconlua** [comment]
Im Edit-Modus darf kein Update über Websocket erfolgen (für alle Control-Types). Wenn der Edit-Modus abgebrochen wird, muss auf zwischenzeitliche Änderungen geprüft werden und Anzeige ggf. aktualisiert werden.

**Comment by fmolleker** [comment]
Edit Modus hinzugefügt. Zeiten werden jetzt korrekt angezeigt und übertragen. Server-seitiges Problem möglich

**Comment by luconlua** [comment]
Server- und Gateway geprüft: Hier passt es auch. Aber im Gerät wird UTC anstatt Lokalzeit angezeigt, daher die 2 Stunden Zeitverschiebung (im Sommer). Korrektur muss im Gerät erfolgen
![Unbenannt](https://user-images.githubusercontent.com/25524211/87044853-68f21580-c1f7-11ea-9b0b-efa259e2a66c.png)

**Comment by luconlua** [comment]
getestet mit pool control

**Comment by wtuz** [comment]
Bei unseren Geräten wird immer die Ortszeit eingegeben. Zeitzonen und Winter/Sommerumschaltung sind im Gerät nicht vorhanden. Zum Schreiben/Setzen erwarten wir einen Unix-Timestamp der die Ortszeit/Systemzeit darstellt.

**Comment by wtuz** [comment]
Alternativ können wir Datum und Uhrzeit als ASCII bereitstellen @KleiberW

**Comment by luconlua** [comment]
Die Datenpunktliste wurde um die Spalte "FormatSpecs" erweitert. Für DateTime Parameter, die in UTC angezeigt werden sollen, müssen die Angabe "noTz" enthalten
