### ISSUE TITLE
Fehlende Infos in der Geräteliste

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#2]
Fehlende Informationen in der Geräteliste ,wenn während des Betriebes des Gateways ein Gerät ans Netzwerk angeschlossen wird.
Siehe Bild - Spalte Schnittstelle / Protokoll / Adresse

![Geräteliste](https://user-images.githubusercontent.com/35223218/86224913-c64bee00-bb89-11ea-87ce-e05c81b1fc4a.PNG)

**Comment by luconlua** [comment]
Info: mit dem nächsten Connect des Gateway sind die Daten da. Sollen aber natürlich sofort kommen
