### ISSUE TITLE
Live Trend zeigt kein Graph an

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#21]
Beim Live Trend wird eine weiße Seite angezeigt.

![image](https://user-images.githubusercontent.com/35223218/86319596-2481db00-bc35-11ea-8fb9-18ed4c49cf57.png)

**Comment by luconlua** [comment]
![Unbenannt](https://user-images.githubusercontent.com/25524211/86566510-10f2af00-bf6a-11ea-9f67-0ac7ace3542b.png)
Hängt evtl. mit Update der Highcharts Komponente zusammen

**Comment by luconlua** [comment]
Fehler betrifft auch den historischen Chart

**Comment by luconlua** [comment]
war wohl ein Versehen

**Comment by luconlua** [comment]
Problem tritt auf, wenn noch keine Werte vorliegen
