### ISSUE TITLE
Archivdatei - Spaltenbeschriftung mit Systemname

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#22]
Zur Unterscheidung (falls mehrere **gleiche** Geräte vorhanden sind) wären eindeutige Spaltenbeschriftungen gut.
 (also    Systemname + Parameter)

**Comment by luconlua** [comment]
Spaltenüberschrift jetzt 
Gerätename/Gruppenname/Parametername [Einheit]
