### ISSUE TITLE
Einheit in der Archiv - Datei 

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#23]
Es wird nur bei einem Parameter in der Spaltenbeschriftung die Einheit mit angezeigt 
(sopra pool control -> Sollwert)

![image](https://user-images.githubusercontent.com/35223218/86320546-6744b280-bc37-11ea-8ab3-6dd03e7c4a4d.png)

**Comment by luconlua** [comment]
es fehlten noch die dynamischen Einheiten
