### ISSUE TITLE
Schreiben von Parametern, die ein Gerät nicht zulässt

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#24]
Das Schreiben des Parameters „Fernbedienung Abdeckung“ bei der sopra-pool-control ist über Modbus nicht erlaubt. 

![image](https://user-images.githubusercontent.com/35223218/86321392-31a0c900-bc39-11ea-8373-6cec353d0867.png)

Nachdem versucht wurde, den Parameter "Fernbedieung Abdeckung" zu setzen, wird ein leeres Feld angezeigt:

![image](https://user-images.githubusercontent.com/35223218/86321407-382f4080-bc39-11ea-87ba-0029c5014a65.png)

**Comment by luconlua** [comment]
Was wird erwartet?
Warum ist der Wert als änderbarer Parameter in der Datenpunktliste eingetragen, wenn er über Modbus nicht verstellt werden kann?

**Comment by wtuz** [comment]
Die Option "Alarm" und "Umschaltung Chlorbedarf" sind über Modbus veränderbar.
Die Option "Fernbedienung Abdeckung" kann nur über das Gerät selbst erst aktiviert/gesetzt werden.

Diese Option hätte man jetzt auch ausmaskieren können, aber dann sieht man eben nicht, dass diese Option aktiv ist.

Erwartet hätte ich, dass einfach nichts passiert.
Über Modbus wird der Parameter ja auch nicht angenommen und der Parameter wird am Gerät auch nicht verändert. 

Wieso wird dann über die Cloud ein leeres Feld angezeigt?

**Comment by luconlua** [comment]
Vorschlag: Aufsplittung in 2 Parameter
1. änderbarer Parameter nur mit den Optionen, die auch änderbar sind
2. Anzeige Status "Fernbedienung Abdeckung"

So ist es sauber und auch für den Anwender klar verständlich umgesetzt.
Eine nicht änderbare Option mit "Ein Fehler ist aufgetreten" anzuzeigen wird für Rückfragen sorgen! Außerdem erscheint in den Logfiles eine Fehlersituation die dann aber eigentlich keine ist => Ebenfalls sehr verwirrend!

**Comment by luconlua** [comment]
Unabhängig vom Vorschlag oben, haben wir das Verhalten wie folgt geändert: Tritt beim Schreiben ein Modbusfehler auf, wird das Register neu ausgelesen und zur Cloud übertragen. D.h. im Fehlerfall wird wieder der aktuelle Wert angezeigt
