### ISSUE TITLE
Update-Trigger Worst-Case Szenario

### ISSUE THREAD

**Issue by luconlua** [luconlua/sopra-cloud#27]
Es sollte ein Test gemacht werden, bei dem der Update Trigger im Gerät alle 500ms auf 1 gesetzt wird. Anschließend Auswertung der Logfiles

**Comment by wtuz** [comment]
Log wurde in Teams hochgeladen

**Comment by luconlua** [comment]
[OneDrive_2020-07-06.zip](https://github.com/luconlua/sopra-cloud/files/4877513/OneDrive_2020-07-06.zip)

**Comment by luconlua** [comment]
Im Testzeitraum treten viele Warnungen dieser Form auf:

2020-01-17 10:54:03.3605 WARN Device-eth0-10_26_70_113_502_1 - Timer callback already running, name:ReadUpdateTriggerTimerCallback-00:00:01 

Die Meldung besagt, dass der Durchlauf des Timers übersprungen wird, weil der vorherige Timerlauf noch nicht abgeschlossen ist.

Das liegt daran, dass das Auslesen der vom Update-Trigger abhängigen Werte schon mal länger als 1 Sekunde dauern kann. Vtml. insbesondere dann, wenn das Auslesen dieser Werte mit dem Auslesen anderer Werte (Timer für normale Abtastraten und OSV Register  zusammenfällt).

Beim Gerät 10.26.70.117 kam es beim Auslesen von Registern (z.B. 1699, 399, 2807, 4013, 199) über einen Zeitraum von ca. 45 Sekunden zu mehreren Timeouts (Timeout: 1 Sek).  Möglicherweise deutet dies auf ein Überlastproblem des Modbus-Servers auf dem Gerät hin?

Abgesehen von den (erwarteten) Meldungen lief das Gateway während des Testbetriebs stabil.

**Comment by wtuz** [comment]
Es wurden zum Test mehrere gleiche Typen an den Modbus angeschlossen, um einen noch besseren Worst-Case zu simulieren.
Das Gerät mit IP 10.26.70.117 lief im Debugmodus, evtl. kann es zu der Zeit auch gewesen sein, dass es in einen Breakpoint gelaufen ist, deswegen ist dieser Log irrelevant und nicht mehr nachvollziehbar.

Relevante logs (für unsere 3 Gerätetypen) waren die Geräte mit IP
10.26.70.114 (soprazon) 
10.26.70.113 (sopra-test)
10.26.70.111 (pool control)

Soweit ich das sehe kamen bei diesen Geräte keine Modbus-Timeouts vor.
