### ISSUE TITLE
Download für Betriebsanleitungen nicht möglich

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#32]
![image](https://user-images.githubusercontent.com/35223218/86716165-38f11980-c021-11ea-8c8a-805d125e3be8.png)

**Comment by luconlua** [comment]
Die Bedienungsanleitungen haben den Stand von der Messe-Version. 
**Müssen die noch aktualisiert werden?  Derzeit sind die Bedienungsanleitungen nur in Deutsch verfügbar - für die anderen Sprachen müssten die noch bereitgestellt werden.**

Am optimalsten wäre es, wenn die Bedienungsanleitungen direkt von der Sopra-Webseite als Permanent-Link heruntergeladen werden könnten.

**Comment by sg-sopraAG** [comment]
Da wir die Bedienungsanleitungen nur unseren Händlern und deren Kunden zur Verfügung stellen, können wir diese nicht öffentlich auf unserer Internetseite plazieren, ist es möglich diese von einem geschützten Händlerbereich aus von der Internetseite downzuloaden?

**Comment by luconlua** [comment]
am besten probieren wir es einfach aus. Können wir ein Beispiel-Link haben?

**Comment by luconlua** [comment]
@sg-sopraAG: Link zu Testzwecken bereitstellen
@Hendrik-Mueller: Link in parameter.xml von Hand ändern. App-Pool der API neu starten und dann ausprobieren

**Comment by luconlua** [comment]
wie vorhin festgelegt, werden die Dokumente jetzt doch in der Sopra Cloud abgelegt (öffentlich zugänglich). 
Sopra stellt uns die Dokumente als PDF zur Verfügung. Wir legen die auf dem Server ab. Links werden in der Übersetzungstabelle entsprechend angepasst.

**Comment by luconlua** [comment]
#95 
Die Dokumente sollen doch auf der Sopra-Webseite abgelegt werden
