### ISSUE TITLE
Wochentagauswahl soll bei Montag beginnen (Wunsch von Sopra)

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#38]
--> Reihenfolge in der Optionsliste in der Datenpunktliste ändern

**Comment by luconlua** [comment]
neue Datenpunktliste vom 07.07 enthält die gewünschte Reihenfolge und wird auch richtig angezeigt

**Comment by wtuz** [comment]
Änderung in der Datenpunktliste enthalten vom 14.7.2020
