### ISSUE TITLE
Problem bei 64bit Variable (32. Bit)

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#39]
Wenn das 32.Bit gesetzt ist, wird das nicht in der Cloud angezeigt
z.B. Modbus-Register 401320 beim sopra-test

![image](https://user-images.githubusercontent.com/35223218/86786353-2fd56c00-c064-11ea-8110-1cd31d9d4cdf.png)

**Comment by luconlua** [comment]
Gateway- und Server-seitig scheint es i.O. 
Problem vermutlich im TypeScript Code zu suchen
