### ISSUE TITLE
Problem bei 64Bit Variable (ab 53. Bit)

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#40]
Wenn ab dem 53. Bit ein Bit gesetzt ist, werden alle Optionen abgewählt, obwohl die Bits gesetzt sind.

z.B. Modbus-Register 1340 beim  sopra-test

![Anmerkung 2020-07-07 145358](https://user-images.githubusercontent.com/35223218/86786602-7aef7f00-c064-11ea-95df-a025469aeba8.jpg)
![Anmerkung 2020-07-07 145327](https://user-images.githubusercontent.com/35223218/86786605-7c20ac00-c064-11ea-9825-ac715f31e755.jpg)

**Comment by luconlua** [comment]
Gateway- und Server-seitig scheint es i.O. 
Problem vermutlich im TypeScript Code zu suchen

**Comment by luconlua** [comment]
Javscript hat (nativ) Probleme mit 64 Bit Werten => Erfordert den Einsatz von BigInt als separates package, da insbesondere Safari BigInt noch nicht nativ unterstützt
