### ISSUE TITLE
Hauptansicht wird nicht automatisch aktualisiert (wenn z.B. ein neues Gerät hinzu kommt)

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#41]
Wenn man bereits an der Cloud angemeldet ist werden hinzukommenden Geräte nicht automatisch angezeigt.
Selbiges gilt auch, wenn man ein Geräte aus der Geräteliste löscht, das nicht mehr mit dem Gateway verbunden ist. 

Entweder man logt sich nochmal aus/ein, oder aktualisiert die Seite z.B. über F5.

**Comment by luconlua** [comment]
in der Endbenutzeransicht funktioniert es. In der Fachmannansicht noch nicht
