### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by KleiberW** [luconlua/sopra-cloud#48]
Für den written Offer (wird in Betriebsanleitung integriert) benötigen wir noch die im IOT Gateway verwendete Open Source Software bzw. Lizenzen.

**Comment by luconlua** [comment]
Wir verwenden Alpine Linux (aktuell in der Version 3.12.0). Grob setzt sich das System aus dem Linux-Kernel, den notwendigen Linux-Paketen und unserer Applikationssoftware zusammen. Es ist leider nicht ganz einfach alle Komponenten mit ihren jeweiligen Lizenzen aufzulisten, da für uns schwer zu erkennen ist, welche Pakete standardmäßig installiert und verwendet werden bzw. welche  Pakete überhaupt einzeln aufgeführt werden müssen. Wir verwenden ein von https://alpinelinux.org/downloads/ bereitgestelltes Image (also ohne Source-Code Änderungen und eigene Kernel-Kompilierung)

Hier die Lizenz-Auflistung (nach besten Wissen)

Linux Kernel: GPL-2.0-only
Linux-Pakete:
- chrony: GPL-2.0-only
- openssh: BSD
- nano: GPL-3.0-or-later
- dhcp: MPL-2.0
- ca-certificates: MPL-2.0 GPL-2.0-or-later
- krb5-libs: MIT
- libgcc: GPL-2.0-or-later LGPL-2.1-or-later
- libintl: LGPL-2.1-or-later
- libssl1.1: OpenSSL
- libstdc++: GPL-2.0-or-later LGPL-2.1-or-later
- zlib: Zlib
- libc6-compat: MIT

Applikationssoftware:
- .NET Core Runtime: MIT
Pakete:
- NLog: BSD 2-Clause
- NModbus: MIT
- System.Device.Gpio: MIT
- System.IO.Ports: MIT
- TimeZoneConverter: MIT
- ExcelDataReader: MIT
- MessagePack: MIT
- Microsoft.CodeAnalysis.CSharp.Scripting: MIT
