### ISSUE TITLE
LiveTrend/Hisotrischer Trend wird mit dem letzten Wert weiter geloggt, obwohl Gerät offline

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#57]
![image](https://user-images.githubusercontent.com/35223218/88162195-4ad1df80-cc11-11ea-9ce9-0a90db371c54.png)

![image](https://user-images.githubusercontent.com/35223218/88162277-6f2dbc00-cc11-11ea-946d-285d3c0d16aa.png)

**Comment by wtuz** [comment]
Im Historischen Trend klappt es noch nicht:

Lila Linie wird im historischem Trend fortgeführt - im LiveTrend wird sie nicht angezeigt (was korrekt ist)

(zum Test wurde die soprazon ausgeschaltet)

![image](https://user-images.githubusercontent.com/35223218/99065038-178fd380-25a7-11eb-8cde-4f3aaabc8ccf.png)

**Comment by luconlua** [comment]
Wie lange wurde das Gerät ausgeschaltet? Es ist zu berücksichtigen, dass im historischen Chart abhängig vom Zeitausschnitt aggregierte Werte angezeigt werden. Bei aggregierten Werten wird die Linie erst dann als Offline angezeigt, wenn das Gerät während des jeweiligen Zeitrasters durchgehend offline war. Z.B. bei 15 Minuten Werten  muss das Gerät 15 Minuten offline gewesen sein.  Das Zeitraster erkennt man, wenn man mit der Maus über die Linie(n) fährt

**Comment by wtuz** [comment]
Also ich meine es war 1h offline ... aber ich werde es nochmal testen

**Comment by luconlua** [comment]
Ergänzung: Die Werte-Aggregation läuft nur, wenn das Gateway online ist.
D.h. um im historischen Chart erkennen zu können, dass die Anlage offline war, muss Sie danach wieder online gewesen sein

**Comment by wtuz** [comment]
Das ist meiner Meinung nach aber sehr unschön, denn ich möchte doch auch sehen, dass das Gerät offline ist, auch wenn es nicht mehr online kommt.... Wieso sollte eine Trendlinie angezeigt werden, wenn doch keine Daten geloggt werden?

------------
Nochmal der Test:
Das Gerät war von ca. 12 uhr bis 15 Uhr abgeschaltet:
Die Linie ist durchgezogen. Es verhält sich auf jeden Fall anders als im Live-Trend. Im Live-Trend ist die Trend-Linie nach ein paar Sekunden weg bzw. unterbrochen.

![image](https://user-images.githubusercontent.com/35223218/99407392-54353500-28ef-11eb-9abe-2a425c2aaddc.png)

**Comment by luconlua** [comment]
Bitte testen

**Comment by wtuz** [comment]
Heute nochmal getestet, 
Im Live Trend wird bei Abschalten des Gerätes nicht mehr weiter geführt -> i.O.
Im Historischem Trend werden die Werte weiterhin fortgeschrieben. Auch in der Archivdatei ist der Wert, der vor dem Abschalten ausgelesen wurde weiter fortgeschrieben worden.

**Comment by luconlua** [comment]
Wie lange war das Gerät abgeschaltet? Bitte Kommentar vom 13.11 berücksichtigen

**Comment by wtuz** [comment]
Ich habe es 2 mal probiert, 1/2 h, und einmal 1h

**Comment by luconlua** [comment]
Wenn Sie für eine 1/2 Stunde unterbrechen und sich anschließend verdichtete Stundenwerte ansehen, wird man die Unterbrechung nicht sehen. Haben Sie verschiedene Zoomstufen ausprobiert? Am besten schauen wir via Teams mal zusammen drauf

**Comment by wtuz** [comment]
ja, habe reingezoomt, keine Unterbrechung zu sehen ..

**Comment by luconlua** [comment]
melde mich gleich via Teams

**Comment by wtuz** [comment]
![image](https://user-images.githubusercontent.com/35223218/108840681-04919400-75d7-11eb-8a24-cb2d2045c035.png)

Wenn Gateway ausgeschaltet wird, funktioniert es, bei Abschalten einzelner Geräte nicht.

**Comment by luconlua** [comment]
ok, Ursache gefunden, wird behoben

**Comment by luconlua** [comment]
Bitte jetzt noch mal testen
