### ISSUE TITLE
sopra pool control - Anzeige Beckenbetrieb

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#59]
Anzeige im Status Umwälzung:
- da fehlt mir die Anzeige ob die Anlage im Whirlpoolbetrieb oder im Schwimmbeckenbetrieb läuft
oder kann man das an der sopra pool control einstellen, was angezeigt werden soll?
![sopra pool control-Anzeige1](https://user-images.githubusercontent.com/67409030/88166107-09443300-cc17-11ea-86ae-f0f6eecc3e07.png)

**Comment by wtuz** [comment]
Wir können natürlich die Symbole für die Umschaltung zwischen den zwei Becken auch auf der Hauptansicht anzeigen.
Daran erkennt man, ob Whirlpoolbetrieb oder Schwimmbadbetrieb aktiv ist. 
Würde das so ausreichen?

**Comment by sg-sopraAG** [comment]
Ja... die sollten in der Spalte "Umwälzung" neben das "Party" Symbol

**Comment by wtuz** [comment]
Wenn dann ist das über eine extra Zeile möglich und mit den zwei Symbolen, wie wir auf den jetzigen Webseite auch verwenden:

![image](https://user-images.githubusercontent.com/35223218/88168444-b79da780-cc1a-11ea-9324-3cf31e0c8ed1.png)

**Comment by sg-sopraAG** [comment]
so können wir das auch machen.

**Comment by wtuz** [comment]
Änderung in Datenpunkttliste vom 27.07.2020 enthalten
