### ISSUE TITLE
Keine Funktion der Standortanzeige

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#6]

**Comment by luconlua** [comment]
Neue Maps-Komponente von Angular Components verwenden

**Comment by luconlua** [comment]
Für bestehende Anlagen auf testcloud.sopra.de muss einmal der Standort erneut gespeichert werden, damit das Geocoding durchgeführt wird. Erst danach wird die Anlage in der Karte angezeigt
