### ISSUE TITLE
sopra pool control - Darstellungsprobleme auf Tablet

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#60]
Es werden momentan nicht die aktuell eingestellten Zeiten an der sopra pool control in der cloud (auf dem Tablet nicht auf dem PC schon) angezeigt für:
- Zeit Normalbetrieb
- Zeit ECO-Betrieb
- Konfiguration Spülung
- Konfiguration Kombibecken
- Herstellerangaben wie Seriennummer usw. fehlen auch
![sopra pool control-Anzeige2-Tablet](https://user-images.githubusercontent.com/67409030/88167549-4b6e7400-cc19-11ea-994c-c8fc0f75617f.png)

auch werden nicht mehrere T1-T3 Schaltzeiten angezeigt und sind nicht einstellbar

**Comment by fmolleker** [comment]
Fehler nicht reproduzierbar

**Comment by sg-sopraAG** [comment]
Fehler steht auch nicht mehr an
