### ISSUE TITLE
sopra pool control

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#61]
Herr Zacher, wie mit Ihnen besprochen können wir die Zeiteinstellungen  (Filtrationszeiten) für den "Winterbetrieb" so realisieren, da kommt die Fa. REHE auch mit klar.

**Comment by wtuz** [comment]
Der Wunsch von Fa. REHE war ja einfach nur mehr einstellbare Filterzeiten die dann für den Winterbetrieb herangezogen werden.
Wobei das aus meiner Ansicht nicht der richtige Weg ist. Denn dann muss man immer wieder alles umkonfigurieren , sobald der Winterbetrieb beginnt bzw. endet.

Als wir das besprochen haben, war das ein grober Vorschlag. Ich bin davon ausgegangen dass Sie das mit REHE konkret abklären und besprechen.
Es muss genau (**schriftlich**) spezifiziert werden, wie so ein Winterbetrieb genau ablaufen soll.
D.h. man muss sich auch über alle Eventualitäten und Szenarien Gedanken machen also z.B.
- was machen wir bei Kombibecken? 
- wird eine automatische Spülung auch im Winterbetrieb ausgeführt?
- was wird mit dem Bodenablaufventil gemacht falls vorhanden?
- in welcher Drehzahl wird umgewälzt? Wenn z.B in ECO-Drehzahl umgewälzt wird, werden dann die Einstellungen "Bodenablaufventil für ECO" beachtet?

usw.


Außerdem sollte das über die Kanäle des Vertriebs (also Hr. Wörner) als auch über Hr. Ganser abgeklärt werden.

**Comment by sg-sopraAG** [comment]
Bitte beschreiben Sie mir Ihren Vorschlag noch einmal kurz, ich bekomme das nicht mehr alles gedanklich zusammen.

Die Indee von Fa. ReHe stelle ich mir so vor:
- Einen Umschaltbutton von Sommer auf Winter (manuell über das Display o. sopra cloud)
- oder autom durch den eingestellten Frostschutzwert
- dadurch wird eine zweite Schaltuhr für Winter aktiviert mit den entsprechend eingegebenen Filterzeiten (viertelstündlich programmierbar) pro Tag
- dies gilt für WP u. SB
- die Heizungsaktivierung bezieht sich dann auf den jeweils eingestellten Wert.
- die Rückspülung bliebe aktiv

Wäre dies so umsetzbar? 
Ich kläre das alles dann final, nach Erhalt Ihres Vorschlages, noch einmal ab und würde dann das alles schriftlich bei Herrn Wörner und Herrn Ganser einreichen.

**Comment by wtuz** [comment]
Hierzu noch die Frage:
Was ist genau der Hintergrund so eines Betriebs nochmal? 
Steht im Vordergrund einfach die Becken zyklisch umzuwälzen? 
Oder steht im Vordergrund die Becken auf eine gewisse Beckentemperatur im Winter zu halten?

Oder beides?

**Comment by sg-sopraAG** [comment]
um eine Kondensatbildung an den Rohrleitungen und an der Filtertechnik im warmen Technikraum und im Winterbetrieb (aktive Überwinterung), wenn das Beckenwasser zu kalt ist zu vermeiden.

**Comment by wtuz** [comment]
D.h. das ein Winterbetrieb immer Vorrang hat ?

Beispiel: Winterbetrieb nur für SB , nicht für WP
Nun läuft gerade die Umwälzung des SB aufgrund des Winterbetriebs. Währenddessen drückt jemand den Taster für den WP. In dem Fall kann aber nicht auf WP umgeschaltet werden?

**Comment by sg-sopraAG** [comment]
Da es sehr unwarscheinlich ist, dass ein WP im Aussenbereich im Winter nicht beheizt wird, kann man den Winterbetrieb nur für das SB vorsehen. 
- es wäre toll, wenn man die "Winterschaltung" mit mehreren kürzeren Pumpen Intervallen an der pool control aktivieren könnte
- es wäre toll, wenn man die "Winterschaltung" mit mehreren kürzeren Pumpen Intervallen autom. über die Frostschutzfunktion oder einen zusätzlichen Außebnfühler (Luft) aktivieren könnte.
Ich würde mir eine "Winterzeitschaltuhr" per Hand oder autom. aktivierbar mit mehreren kürzeren Schaltinverallen vorstellen für das SB. Die WP Umschaltung und Regelung muss aktiv bleiben, dann ist halt das SB in dieser Zeit aus.

**Comment by wtuz** [comment]
Aber nochmal als Hinweis:

Das Problem ist, man kann für den Whirlpoolbetrieb max. 300 min, also 5 Std. einstellen. Das ist schon eine ziemlich lange Zeit, bei der das SB dann im Winterbetrieb nicht umgewälzt werden würde.

Zusätzliche Problematik, wenn ein Taster für die Umschaltung des WP verwendet wird: Hier ist es so, dass die Zeit immer wieder neu gestartet wird, sobald man den Taster betätigt. d.h. im Endeffekt dass der WP-Betrieb unendlich lange aktiv sein könnte, wenn man z.B. jede 4 Std. den Taster betätigt.

**Comment by wtuz** [comment]
So weit ich das mit dem Außenfühler verstehe  soll es so funktionieren:
Ich habe einen Schalter, bei dem ich umstelle zwischen Sommer/Winterbetrieb.
Zusätzlich über einen Außentemperaturfühler wird die Außentemperatur detektiert. Wenn die Außentemperatur **unter** einem bestimmten Schwellwert ist, beginnt die Umwälzung in Intervallen.

Bei der Idee mit dem Außenfühler sehe ich noch ein Problem:
Beispiel:
Ich stelle über den Umschaltbutton um auf Winterbetrieb. Sobald die Steuerung auf Winterbetrieb ist sind die anderen eingestellten Umwälzzeiten nichtig - richtig?
Wenn die Außentemperatur weit genug unten ist beginnt die Intervallschaltung der Pumpe.
Bis hier hin so weit so gut.

Wenn die Außentemperatur jedoch wieder steigt hört die Intervallschaltung der Pumpe auf. 
Wenn die Tage aber immer wärmer werden, und die Steuerung  noch auf Winterbetrieb ist, oder wenn es einfach im Winter mehrere Tage wärmer ist und man **über** dem Schwellwert des Außentemperaturfühlers ist, dann wird unter Umständen nie umgewälzt?

**Comment by luconlua** [comment]
Ist der Punkt noch offen?

**Comment by sg-sopraAG** [comment]
Ja, da ist Herr Zacher gerade dran.

**Comment by wtuz** [comment]
@sg-sopraAG  Ich warte noch auf ihre Antwort per E-Mail !

Ansonsten kann das hier eigentlich geschlossen werden - das hat ja in 1. Schritt nichts mit der Cloud zu tun.
