### ISSUE TITLE
sopra pool control - Betriebsdaten

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#62]
Diagnose Betriebsdaten:
Betriebsstunden:  kann man hier die Minutenangaben auch in Stunden und Minuten
![sopra pool control-Anzeige-3](https://user-images.githubusercontent.com/67409030/88168837-4dd1cd80-cc1b-11ea-9ce8-903fe00aee02.png)
 angeben?

**Comment by wtuz** [comment]
Änderung in Datenpunktliste vom 28.07.2020 enthalten

**Comment by wtuz** [comment]
Nochmals eine Korrektur ab Datenpunktliste vom 18.08.2020 + soprazon Softwareversion ab V2.0g (Ergänzung stepWidth) damit Nachkommastelle angezeigt wird
