### ISSUE TITLE
sopra pool control - Anzeige Abdeckung

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#63]
Anzeige Abdeckung:
- wird hier, wenn eine Grando Abdeckung bedient werden möchte, der Zustand ob "offen" oder "geschlossen" angezeigt?
![sopra pool control-Anzeige-4](https://user-images.githubusercontent.com/67409030/88169186-f08a4c00-cc1b-11ea-9269-c71ddd181446.png)

**Comment by wtuz** [comment]
Das Linke Icon bei "Abdeckung/Attraktion) zeigt an ob offen oder geschlossen.
Es steht allerdings nur ein Digitaleingang zur Detektierung zur Verfügung - daran hat sich nichts geändert und war schon immer so

Ist der Digitaleingang offen, ist die Abdeckung geschlossen, 
ist der Eingang geschlossen, wird die Abdeckung als offen angezeigt

**Comment by wtuz** [comment]
@sg-sopraAG    ist dieser Punkt dann soweit erledigt? (siehe Kommentar oben?

**Comment by sg-sopraAG** [comment]
ja.
