### ISSUE TITLE
sopra pool control - Beschriftung Trend

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#67]
Anzeige der Trendkoordinaten Beschriftungen:
- diese sollten links vor den Werten stehen
- diese sollten von rechts dann lesbar sein, also um 180° nach links gedreht

![sopra pool control-Anzeige-6](https://user-images.githubusercontent.com/67409030/88170935-c9814980-cc1e-11ea-9787-47632ff7a3da.png)

**Comment by sg-sopraAG** [comment]
hier das richtige Bild

![sopra pool control-Anzeige-7](https://user-images.githubusercontent.com/67409030/88171008-ea499f00-cc1e-11ea-8479-9263be15a07b.png)

**Comment by Hendrik-Mueller** [comment]
Die Einheit kann momentan über Highcharts nicht nach links verschoben werden.
Der Text wurde um 180° nach links gedreht.

**Comment by luconlua** [comment]
Man könnte auch alle Y-Achsen auf der linken Seite anzeigen. Dann hätte man die Problematik mit dem verdrehten Text nicht. Sollen wir es so machen ?

**Comment by sg-sopraAG** [comment]
so können wir das lassen
