### ISSUE TITLE
sopra test premium - Yout

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#68]
"Yout" das kann keiner verstehen, was dieser Wert heißt bzw. bedeutet. 
- Bitte in der jeweiligen Landessprache beschriften

![sopra pool control-Anzeige-8](https://user-images.githubusercontent.com/67409030/88171434-98554900-cc1f-11ea-8df0-f802fca57093.png)

**Comment by KleiberW** [comment]
Der Text "Yout" ist identisch zum Anzeigetext des Gerätes, insofern wäre eine Änderung im Portal nicht durchgängig zur Anzeige undBetriebsanleitung des Gerätes.

**Comment by sg-sopraAG** [comment]
Dann sollte man es evtl. durchgängig ändern.
Was bedeutet den "Yout:" eigentlich? Ist das irgendwo beschrieben?

**Comment by KleiberW** [comment]
In der Regelungstechnik ist Y die üblich verwendete Bezeichnung für Regelgröße bzw. Stellgröße. Die Bezeichnungen im Regelkreis sind genormt, Yout beschreibt die Reglerausgabe des Regelkreises. In diesem Fall eben die Dosierleistung bzw. Reglerausgabe der Chlorreglers. Der Begriff Yout wird seit vielen Jahren in unseren Mess- und Regelgeräten verwendet und ist auch in der Betriebsanleitung als Regelgröße bzw. Dosierausgabe beschrieben.

**Comment by KleiberW** [comment]
Wir könnten das aber auch die Yout Anzeige aus der Kachelansicht herausnehmen da dies nicht unbedingt auf der Hauptansicht gezeigt werden muss.

**Comment by sg-sopraAG** [comment]
Ich stelle halt die Frage aus der Sicht des Endkunden bzw. Benutzers, da könnte man dies tatsächlich ausblenden.
Bei dem Benutzer + würde ich es drin lassen wollen.

**Comment by wtuz** [comment]
Änderung in Datenpunktliste vom 27.07.2020 enthalten
