### ISSUE TITLE
soprazon premium 19 - Darstellung der Betriebsart

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#69]
Anzeige für Automatik-/Handbetrieb:
- bitte hier die jeweiligen Symbole wie bei den anderen Geräten verwenden

![sopra pool control-Anzeige-9](https://user-images.githubusercontent.com/67409030/88171750-2af5e800-cc20-11ea-80ea-ff0183f486e7.png)

**Comment by wtuz** [comment]
Es gibt für soprazon allerdings 3 Betriebsarten: Automatik/Hand/Aus. 
D.h. die Betriebsart über 1 Symbol (das zwischen Automatik und Hand wechselt) wie bei der sopra-pool-control darzustellen ist bei der soprazon nicht möglich.

Die Durchgängigkeit würde auch beim sopra - test premium fehlen. 
Beim sopra-test ist eine Darstellung über Icons sowieso nicht möglich, da hier mehrere "Bedingungen" gleichzeitig zutreffen können (z.B. Hand und Regler Stop)

![image](https://user-images.githubusercontent.com/35223218/88188674-74eac800-cc38-11ea-81d6-c05e47c930d9.png)

**Comment by sg-sopraAG** [comment]
Die Anzeige "Hand / Auto / Aus" gibt es bei der pool control doch auch schon
Hand  = Handbetrieb 
Autom. Zeichein = Automatikbetrieb
und zusätlich verfärbt sich die Anzeige im Onmodus auf grün !
Dann haben Sie doch alles über 1 Symbol!

**Comment by wtuz** [comment]
Änderung in Datenpunktliste vom 27.07.2020 enthalten

**Comment by wtuz** [comment]
@sg-sopraAG   Hr. Guckert, ich habe Ihnen eine Freigabe für unsere Testanlage erteilt.

Bitte schauen Sie sich die Sache bezüglich der Betriebsartanzeige nochmal an.

Problem bei der Soprazon: 
Die Philosophie war bisher bei derartigen Anlagen dass man die Betriebsart nicht von der Ferne umstellen kann. 
Das gleiche gilt bei der sopra-test im übrigen auch.
Es kann bei beiden Geräte die Betriebsart nicht umgestellt werden, deshalb wäre aus meiner Sicht konsistent gewesen, wie es vorher war.

**Comment by luconlua** [comment]
Es wurde ein weitere Datenpunkt "Betriebsartanzeige" mit Symbolen ergänzt (kann nicht verstellt werden)

**Comment by wtuz** [comment]
@sg-sopraAG   Ist die Anzeige nun so i.O ?  siehe Testanlage 2

**Comment by sg-sopraAG** [comment]
ja... sieht gut aus. Wechselt die Anzeigenfarbe "grün" auf "grau", wenn die Anlage ausgeschaltet ist?

**Comment by wtuz** [comment]
Bei der soprazon wird entweder ein grünes Automatik Symbol, grünes Handsymbol, oder ein Aus-Symbol (grau) angezeigt.
Bei der sopra-test ist entweder Hand oder Automatik Symbol aktiv (grün)
