### ISSUE TITLE
Keine Aktualisierung der Parameter bei Änderung am Gerät

### ISSUE THREAD

**Issue by wtuz** [luconlua/sopra-cloud#7]
Bei Änderung eines Parameters am Gerät wird der Wert nicht aktualisiert - UpdateTrigger wird am Gerät auch nicht zurückgesetzt

**Comment by luconlua** [comment]
Die Timer werden nach dem Start direkt wieder beendet (es muss eine Referenz auf den Timer gespeichert werden)

**Comment by luconlua** [comment]
Fehler betrifft auch den OSV Timer
