### ISSUE TITLE
soprazon premium 19 - Strom und Anlagenleistung in Hauptanzeige

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#70]
Hauptanzeige:
- in der ersten Spalte sollten noch die Angaben "Ampere" und die eingestellte Leistung "in g/h" stehen

![sopra pool control-Anzeige-10](https://user-images.githubusercontent.com/67409030/88172151-ce46fd00-cc20-11ea-925c-d551ccee0950.png)

**Comment by sg-sopraAG** [comment]
Hauptanzeige:
- zusätzlich noch die jeweilige Betriebsart "Automatik" oder "Hand" mit den Symbolen wie bei den anderen Geräten

**Comment by wtuz** [comment]
Hr. Guckert, es gibt aber maximal bis zu 3 Anlagenleistungen. Sollen dann ggf. alle 3 Anlagenleistungen angezeigt werden?
(Anlagenleistung für Chlorbedarf Schimmbadbetrieb / Schwimmbadbetrieb ECO / Whirlpoolbetrieb)

**Comment by sg-sopraAG** [comment]
Nein nur die aktuelle Leistung mit der jeweils dazugehörigen Betriebsart, also SB / SB ECO / WP

**Comment by wtuz** [comment]
Änderung in der Datenpunktliste vom 27.07.2020 enthalten
