### ISSUE TITLE
Festlegung/Anzeige der verschiedenen Benutzerebenen

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#72]
Sind die verschiedenen Benutzerebenen schon in der test cloud anzeigbar? 
Ich komme da mit meinem 2. Account nicht rein.

**Comment by luconlua** [comment]
Nehme an "guckert@sopra.de" (Rolle=Endbenutzer) ist gemeint? Wie ist die Fehlermeldung?

**Comment by sg-sopraAG** [comment]
ja... es gibt aber keine Fehlermeldung, wenn ich mit meinem 2. Zugangsdaten für den "Endkundenbereich" anmelde dann komme ich automatisch wieder in den "Servicebereich".

**Comment by sg-sopraAG** [comment]
Können Sie mir einen neuen Account einrichten für den Endkundenbereich?

**Comment by luconlua** [comment]
Sollten nachgehen, warum es Probleme gibt. 
Der letzte Login war am 13.05
Screenshots wären noch hilfreich

**Comment by sg-sopraAG** [comment]
Jetzt komm diese Meldung:
![Anmerkung 2020-07-23 152210](https://user-images.githubusercontent.com/67409030/88291453-8d221c00-ccf8-11ea-808a-a12c19f4b11d.png)
Markierter Punkt Nr. 1:
wenn ich darauf klicke sehe ich nicht das Passwort in Buchstaben!

Wenn ich danach auf "Passwort vergessen" klicke  (2.) kommt dieses Fenster
![Anmerkung 2020-07-23 152529](https://user-images.githubusercontent.com/67409030/88291612-c9ee1300-ccf8-11ea-863b-ff1d7eabfc53.png)

**Comment by luconlua** [comment]
ok - Passwort vergessen funktioniert anscheinend nicht (habs aber gerade erfolgreich getestet)
Welcher Browser wird verwendet? Welches Betriebssystem?  
Können wir mit Teamviewer auf den "Problem"-Rechner?

**Comment by sg-sopraAG** [comment]
Firefox
Windows 10
ja können wir.
Sie können mich Mobil unter : 0172 2900 599 erreichen

**Comment by luconlua** [comment]
Doppelt #83
