### ISSUE TITLE
sopra Cloud Datenschutzfragen

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#73]
- Das Passwort für den Cloud Zugang sollte, lt. Datenschutzrichtlinien >5 stellig sein und sollte nicht nur aus Ziffern oder Buchstaben bestehen, ist das momentan so?
- wird bei der Passwortvergabe der user dazu gezwungen diese Anforderungen einzugehen?

**Comment by luconlua** [comment]
Passwortkriterien: 8 oder mehr Zeichen, Groß- und Kleinbuchstaben und mind. eine Zahl
