### ISSUE TITLE
IDSRV canceled requests

### ISSUE THREAD

**Issue by luconlua** [luconlua/sopra-cloud#74]
![Unbenannt](https://user-images.githubusercontent.com/25524211/88510784-04e79380-cfe4-11ea-8613-1368dcfd2972.png)

**Comment by fmolleker** [comment]
auf lucon-projects mit aktuellen build nicht reproduzierbar. Liegt es vielleicht an der Umgebung?

**Comment by luconlua** [comment]
Die SPA darf nicht im root Verzeichnis gehostet werden, sondern in einem Subverzeichnis (/app). Da der Serviceworker sonst auch für die IDSRV Webseite gilt.

Wurde auf testcloud.sopra.de angepasst. Fehler ist seit dem weg
