### ISSUE TITLE
sopra test cloud - Account Löschungen - sopra AG

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#76]
Es wurden anscheinend unsere Accounts (sopra AG) gelöscht. 

Testanlage 1 in der sopra AG
- Was muss ich nun tun um mich wieder anzumelden?
- Seriennummer eingeben beim Login?

Testanlage 2 bei Fa. Henne
- Hier muss ich wissen, was zu tun ist, wenn diese am Dienstag o. Mittwoch installiert ist.
  denn die Seriennummer habe ich mir hier nicht notiert

**Comment by wtuz** [comment]
Aufgrund eines Updates werden alle Gateways/Anlagen aus der Cloud gelöscht.

Die Anlagen müssen also wieder neu hinzugefügt werden.

Testanlage 1:
Serien-Nr: nA8pFbh69u
Passwort: abcABC123!

Testanlage 2
Serien-Nr:  GwKzZ9eJHD
Passwort: abcABC123!

Dazu brauchen Sie noch die Updates zu den Geräten.

Die lasse ich ihnen perE-Mail zukommen.
