### ISSUE TITLE
Anlage hinzufügen-Formular automatische Einträge

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#79]
Wieso stehen automatisch in diesem Anmeldeformular unter "Seriennummer" der Besitzername und unter "Passwort" das Anmeldepasswort für die cloud ?
![Anmerkung 2020-07-28 092341](https://user-images.githubusercontent.com/67409030/88633108-d980a980-d0b4-11ea-969f-34790468e7c2.png)

**Comment by luconlua** [comment]
Das Formular wird nicht mehr verwendet, da neues Freigabekonzept zum Einsatz kommt
