### ISSUE TITLE
sopra cloud Login-Symbole auf Laptop

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#80]
@luconlua 
- Wie kommen diese Symbole in blau (s. screenshot) zustande, welche nur auf meinem Laptop zu sehen sind auf der Workstation nicht bei beiden arbeite ich mit Firefox (gleiche Version)?
![Anmerkung 2020-07-28 111905](https://user-images.githubusercontent.com/67409030/88645818-d988a580-d0c4-11ea-8d8e-21598ee24aaf.png)

**Comment by luconlua** [comment]
Die kommen sehr wahrscheinlich von einem zusätzlich installierten Passwortmanager o.ä. auf dem PC/Notebook
