### ISSUE TITLE
sopra cloud Adminrechte für sopra AG

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#82]
@luconlua 
ich benötige noch die Adminrechte für die sopra cloud, oder haben wir diese bewusst noch nicht bekommen?

**Comment by luconlua** [comment]
kp, für welchen Account?

**Comment by sg-sopraAG** [comment]
für s.guckert@t-online.de

**Comment by luconlua** [comment]
abmelden und wieder anmelden, dann sollten Sie Admin-Rechte haben
