### ISSUE TITLE
sopra AG-Anmeldungsprobleme mit dem 2. Account "guckert@sopra.de"

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#83]
@luconlua 
ich komme da immernoch nicht drauf, trotz der Passwort vergessen Funktion.
![Anmerkung 2020-07-29 121040](https://user-images.githubusercontent.com/67409030/88787727-a01f6b00-d194-11ea-99b4-49aab834ac52.png)

**Comment by luconlua** [comment]
mit Chrome geht es auch nicht?
Funktioniert es im Büro?
Können Sie von einem anderen PC probieren?

**Comment by sg-sopraAG** [comment]
Mit Chrome geht es auch nicht, auch nicht von meiner work station aus.
- kann es sein, dass ich mit "guckert@sopra.de" nicht mehr registriert bin?
- kann es sein, dass bei einer Anmeldung, wenn das PW auf dem Browser gespeichert ist, es zu Störungen kommt?

**Comment by wtuz** [comment]
Es ist nur der Account s.guckert@t-online.de registriert

**Comment by wtuz** [comment]
guckert@sopra.de ist gesperrt

![image](https://user-images.githubusercontent.com/35223218/88790748-e8408c80-d198-11ea-873b-614b5c0e1297.png)

**Comment by sg-sopraAG** [comment]
wie kann ich diesen account wieder frei geben? Die Adminrechte habe ich jetzt

**Comment by wtuz** [comment]
Ich vermute mal bisher nur durch Löschen des Accounts möglich, und dann wieder registrieren.

**Comment by sg-sopraAG** [comment]
habe ich gemacht, 
- wo sehe ich dann die Anmeldung im Adminbereich?  
- bekommt der neue Account dann automatisch eine Rückmeldung ob die Anmeldung erfolgt ist?

**Comment by sg-sopraAG** [comment]
@luconlua 
Die Anmeldefunktion "Registrierung" scheint nicht zu funktionieren. Es kommt auch keine Rückmeldung, dass die Registrierung erfolgreich oder nicht war und man gelangt direkt wieder auf einem neuen Login-Fenster.

**Comment by wtuz** [comment]
unter Benutzerverwaltung -> Benutzerliste sehen Sie alle Registrierten User
Bei der Registrierung bekommen Sie eine E-Mail, bei dem Sie die Registrierung über einen Code nochmal bestätigen müssen, danach bekommen Sie keine weitere Benachrichtigung

**Comment by sg-sopraAG** [comment]
Die Benutzerliste hatte ich schon offen, die Anmeldung kommt aber dort nicht an und 
es kommt  keine Mail mit einem Code an! 
Die Funktion schein gestört.

**Comment by wtuz** [comment]
Ich habe es gerade getestet, bei mir funktioniert es  (normaler PC Win10 mit Firefox)

**Comment by wtuz** [comment]
Evtl. im Spam Ordner nachschauen

**Comment by sg-sopraAG** [comment]
im Spam ist nichts

**Comment by luconlua** [comment]
> wie kann ich diesen account wieder frei geben? Die Adminrechte habe ich jetzt

Mit der Passwort vergessen Funktion, nur funktioniert die bei Ihnen nicht, ebenso die Registrierung
Rufe Sie ab 15:00 an. Sind Sie dann zu erreichen?

**Comment by sg-sopraAG** [comment]
Bin um 15:00 im Büro,

**Comment by sg-sopraAG** [comment]
Über das Tablet hat es nun für "guckert@sopra.de" geklappt. Über den PC nicht. 
Auch bei einem Versuch eines Technikausschusskollegen von Bremen hat eine Registrierung vom PC nicht geklappt.

**Comment by luconlua** [comment]
das hängt irgendwie mit dem zScaler Web-Gateway zusammen, für das wir noch keine Lösung haben

**Comment by luconlua** [comment]
Wir haben Änderungen an der Konfiguration des Webservers vorgenommen. Bitte noch mal testen, ob es sich gebessert hat.
Es kann beim ersten Öffnen der Webseite nach der Umstellung zu einer Fehlermeldung kommen (dann F5 im Browser drücken). Der erste Logout kann ebenfalls fehlschlagen

**Comment by sg-sopraAG** [comment]
Keine Besserung, es bestehen seit neustem auch Probleme mit der Anmeldung vom 1. Account "s.guckert@t-online.de"
- Absturz beim Anmelden eines neuen Benutzers 
- Absturz ohne Tätigkeit
- Probleme bei der Wiederanmeldung danach (funktioniert nur manchmal wenn ich die URL wieder neu eingebe, über die Lesezeichenfunktion kommen dann wieder Störungen (Firefox neu; Windows 10)

von meinem Tablet aus (IPad pro) funktioniert es immer.

**Comment by luconlua** [comment]
Wenn es noch Anmeldeprobleme gibt, neuen Eintrag erstellen
