### ISSUE TITLE
sopra pool control - Anzeige SB obwohl WP manuell gestartet wurde

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#84]
Die SB/WP - Anzeige in der cloud folgt nicht der manuellen Umschaltung an der pool control von Schwimmbad (SB) auf Whirlpool (WP). An der pool control wird WP angezeigt.
![Anmerkung 2020-07-29 122520](https://user-images.githubusercontent.com/67409030/88789397-01483e00-d197-11ea-92ce-41fe9aca87b6.png)

**Comment by wtuz** [comment]
Ok, da sind die zwei Anzeigen vertauscht - ist in der Datenpunktliste der Cloud verkehrt herum angegeben...

**Comment by wtuz** [comment]
@luconlua  
Die ICONS müssen aktualisiert werden, im Teams habe ich die geänderten ICONS abgelegt - Ordner Update_28.07.2020
