### ISSUE TITLE
sopra pool control - Konfiguration Licht - Anzeigedauer - falsche Zeiteinheit in der cloud

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#85]
@wtuz 
hier wird in der cloud Ansicht als Zeiteinheit "s" für die Anzeigedauer angezeigt.
![Anmerkung 2020-07-29 145107](https://user-images.githubusercontent.com/67409030/88802415-5726e100-d1ab-11ea-97bd-244a7809af03.png)
auf dem Gerät werden "Minuten" angezeigt.
![IMG_0816](https://user-images.githubusercontent.com/67409030/88802569-89d0d980-d1ab-11ea-92cc-d5b9796886ba.jpg)
![IMG_0817](https://user-images.githubusercontent.com/67409030/88802601-948b6e80-d1ab-11ea-9f6d-e5f4eed62298.jpg)

**Comment by wtuz** [comment]
Wird von der Gerätesoftware (pool control) falsch übertragen - ist mit dem nächsten Update bereinigt
