### ISSUE TITLE
Fragen Alarmierung

### ISSUE THREAD

**Issue by luconlua** [luconlua/sopra-cloud#89]
Wie lange sollen Alarme in der Cloud aufbewahrt werden? Reicht 1 Jahr?

**Comment by sg-sopraAG** [comment]
Ja... das reicht
- kommt dann vorher eine Meldung, dass diese gelöscht werden?
- kann man die gespeicherten Alarme downloaden oder anderweitig speichern?
- kann man die gespeicherten Alarme ausdrucken?

**Comment by KleiberW** [comment]
Aus meiner Sicht ist ein Jahr völlig ausreichend, allerdings würde ich auch die Anzahl der Meldungen begrenzen auf z.B.max. 500 Meldungen. Denn es gibt sicherlich auch Systeme welche falsch konfiguriert sind bzw. werden und deshalb sehr häufig Meldungen absetzen.

**Comment by luconlua** [comment]
Denke, dass kann man später noch mal optimieren, wenn Erfahrung vorliegt. z.B. über eine zusätzliche Hysterese, etc.
