### ISSUE TITLE
sopra pool control - Fehler-/Störmeldung "Messwasser ?"

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#91]
@KleiberW 
@wtuz 
diese "Störmeldung" muss ja eigentlich im Falle einer Filterzeitabschaltung nicht aktiviert werden. In fast allen Fällen im Privatpoolbereich, wird das Messwasser nicht über eine separate Messwasserpumpe dem Pool entnommen, sondern wird der Reinwasserleitung hinter der Filteranlage in einem Bypassanschluss entnommen und wieder zurück geführt. Wir bekommen momentan bei jeder über die Zeitschaltung abgeschalteten Filterpumpe eine "Meßwasser ?" Störung angezeigt. Dies führt dazu, dass diese alle 4 Min. im Protokoll steht. Kann man diese Meldung irgendwie umprogrammieren, sodass diese Störung nur gemeldet wird, wenn die Filterpumpe und der separate Durchflusswächter aktiv sind?
D.h. man müsste eine Auswahl in der Konfigurierung treffen können Meßwasserpumpe ja/nein.

**Comment by KleiberW** [comment]
@sg-sopraAG dafür gibt es bereits jetzt schon eine Lösung - Üblicherweise wird von der Filtersteuerung ein Kontakt "Umwälzung Ein" auf den Digitaleingang 2 des Sopratest Premium 17 verdrahtet. Man muss den DI2 im Sopratest auf Regler Stopp konfigurieren damit die Dosierung abschaltet wenn keine Umwälzung läuft. Allerdings wird dabei dann die Meldung "Messwasser ?" aktiv und es werden Messwerte des stehenden Messwassers angezeigt. Wir haben seit Jahren auch die Möglichkeit integriert das Sopratest über Digitaleingang 2 auf "Standby" umzuschalten damit Fehler, Alarme und die Messwertanzeige ausgeblendet werden bei abgeschalteter Umwälzung. Insofern sollte im Menü Digitaleingang 2 die Zuordnung auf "Standby" eingestellt werden - dann wird bei abgeschalteter Umwälzung die Dosierung abgeschaltet und der Messwasserfehler und Alarme nicht aktiviert. Das sollte das Problem auf jeden Fall lösen - bitte testen

**Comment by sg-sopraAG** [comment]
@KleiberW 
verstehe ich das richtig, dass es zwei Möglichkeiten gibt?
1. DI2 auf Regler Stopp konfigurieren
2. DI2 auf Zuordnung "Standby" einstellen
kann man dies über die cloud machen?

**Comment by sg-sopraAG** [comment]
@KleiberW 
Was passiert nach der Zuordnung in "Standy" mit den Fehlermeldungen "Messwasser ?" bei einer Umschaltung Schwimmbecken- auf Whirlpoolbetrieb wenn die die Pumpe für eine Zeit x in der Umschaltphase ausgeschaltet wird, oder bei der Rück- bzw. Klarspülungumschaltung wenn auch hier die Pumpe für eine Zeit x in der Umschaltphase ausgeschaltet wird?

**Comment by KleiberW** [comment]
@sg-sopraAG korrekt man kann DI2 auf verschiedene Funktionen zuordnen, je nachdem wie der DI2 verdrahtet ist muss die Zuordnung vor Ort an der Anlage gewählt werden. DI2 = Regler stopp wird häufig auch zum Anschluss von Niveausonden verwendet oder auch anderweitige Möglichkeiten zur sicherheitsbedingten Abschaltung der Dosierung. In diesem Fall sollten wir das an Ihrem Beckenaufbau ausprobieren ob noch eine Fehlermeldung generiert wird bei Spülung oder Umschaltung Whirlpool. Normalerweise dürfte bei Auswahl DI2=Standby keine Meldung "Messwasser?" mehr generiert werden bei Umschaltung Whirlpool, Umwälzabschaltung oder auch Spülungen.
Sofern an Ihrer Anlage der DI2 nach unserer Empfehlung mit dem Umwälzkontakt der Filtersteuerung verdrahtet ist müssen Sie nur die Einstellung DI2 = Standby wählen. Falls der Umwälzkontakt nicht auf DI2 am Sopratest verdrahtet ist wäre dies ohnehin erforderlich.

**Comment by KleiberW** [comment]
@sg-sopraAG da beim Einschalten der Umwälzung aus dem Standby-Mode die Messwasser ? - Meldung noch kurzzeitig erscheint ist noch eine Softwareänderung am Sopratest erforderlich damit die Messwasserstörung verzögert wird. Werden wir zeitnah integrieren.
