### ISSUE TITLE
Störmeldeliste- Anstehende Meldungen werden alle 4Min. wieder neu angezeigt?

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#92]
@luconlua @wtuz @KleiberW 
dies führt zu einer ellenlangen Störmeldeliste, wenn die Anlage z.B. über Nacht nicht aktiv ist. Kann mann eine Störmeldung nicht nur einmal anzeigen lassen bei der Entstehung und danach einfach eine zweite Meldung generieren, wenn die Strömeldung quittiert wurde?

**Comment by luconlua** [comment]
Alarme in der Alarmhistorie werden aktuell nicht  korrekt beendet, wenn der Fehler geht. Update ist noch für heute geplant

**Comment by luconlua** [comment]
Der Versand von Störmeldungen per Mail kann jetzt ebenfalls getestet werden.

**Comment by sg-sopraAG** [comment]
@KleiberW @wtuz 
der Fehler ist mit der geänderten Software noch nicht ganz behoben. Die Testanlage 1 schaltet sich morgens immer um 8:00 Uhr ein danach um 8:00:25 kommt die Meldung "Messwasser ?" und um 8:00:34 verschwindet sie wieder !? Könnte das die Dosierzeitverzögerung sein? Die ist bei uns auf 10min eingestellt.

**Comment by KleiberW** [comment]
@sg-sopraAG @wtuz  ich habe das schon überprüft und gesehen dass bei Ihrer Anlage die Messwasserverzögerungszeit auf 0 min 0sec eingestellt war, das bedeutet dass sofort nach Umwälzfreigabe der Fehler durchkommt ohne Beachtung der Anlaufzeit der Pumpe. Deshalb habe ich jetzt die Messwasserverzögerungszeit auf 30sec gestellt. Ich denke jetzt müsste es funktionieren.

**Comment by sg-sopraAG** [comment]
@KleiberW 
das bedeutet aber doch das z.B. die soprazon 30s länger produziert, oder? Und dass alle Dosierungen 30s länger dauern und somit es zu Überschwingern kommen wird. Aus diesem Grund habe ich das bei unser "kleinen" Testanlage 1 auf "0" gesetzt.
Kann man das Problem auch irgendwie auf eine andere Weise lösen?

**Comment by KleiberW** [comment]
@sg-sopraAG die Soprazon sollte mittels Freigabekontakt der Filtersteuerung verriegelt sein und auch sofort abschalten wenn die Umwälzpumpe abschaltet (es sind zwei Ausgänge in der Filtersteuerung vorgesehen (K16 und K18) Ein Kontakt für die Sopratest zum Umschalten auf Standby, ein Kontakt für Extern Stop der Soprazon. Messwasser Stop Fehler kommt eigentlich nur bei verschmutztem Messwasserfilter vor oder es macht jemand das Messwasser zu, dann schaltet die Dosierung verzögert ab. Ein Überschwingen kommt deshalb nicht vor im Normalbetrieb/Standby. Möglicherweise ist bei Ihrer Anlage auch eine Messwasserverzögerungszeit mit 5 oder 10 Sekunden ausreichend. Das können wir dann noch testen.

**Comment by wtuz** [comment]
@sg-sopraAG
Bezugnehmend auf die heutige TEAMS-Besprechung habe ich das gerade bei mir getestet. (mit der aktuellen Version V2.00e der sopra-test)

Ohne dass man eine Messwasserverszögerungszeit von mindestens 3 Sek. einstellt funktioniert das momentan noch nicht 100%. 
Wenn man das nicht macht, kann es sein dass ab und an der Messwasserfehler auftaucht.

Normalerweise geht man verdrahtungstechnisch wie folgt vor:
K16 und K18 sind Freigabekontakte. Beide Ausgänge schalten wenn die Umwälzung aktiv ist.

Also verdrahtet man von K16 der sopra pool control auf den DI2 des sopra-tests (Dieser DI2 der sopra-test wird auf Standby konfiguriert - wie Hr. Kleiber schon erwähnt hat)

Den zweiten Ausgang K18 der pool control sollte man dann auf die soprazon DI2 verdrahten (Umwälzverriegelung!), 
**und übrigens nicht wie Hr. Kleiber gemeint hat auf den DI7 ext. Stop. der soprazon!** Das würde zwar auch funktionieren, aber dann würde immer der Stop-Alarm an der soprazon angezeigt werden.

Die Umwälzverriegelung ist übrigens auch sehr wichtig, da z.B. bei einer Klarspülung sonst auch die soprazon anlaufen würde !
Das habe ich u.a. auch schon selbst bei Anlagen vor Ort von sopra-Partnern gesehen, dass das nicht so gemacht wird und die Anlage dann bei Klarspülung anläuft.

Die Messwasserverzögerungszeit spielt- so weit ich das sehe - gar keine Rolle bezüglich der soprazon.
Denn wenn die sopra-test auf Standby geht, wird sofort das Reglerrelais abgeschaltet. Außerdem ist gleichzeitig die Umwälzverriegelung aktiv (wenn man das so verdrahtet wie oben vorgeschlagen)
Deshalb kann es so nie zu Überschwingern kommen.

Ich habe mir erlaubt bei Ihrer Testanlage (1)  die Messwasserverzögerung auf 5s zu setzen.
Bitte testen Sie das auch nochmal. So weit ich das beurteilen kann funktioniert das aber alles - ohne Messwasserfehler wenn die Umwälzung abschaltet.

**Comment by wtuz** [comment]
@sg-sopraAG   Bitte diesen Punkt schließen, wenn es keine Probleme mehr gibt
