### ISSUE TITLE
Text "Chlorbedarf" Soprazon

### ISSUE THREAD

**Issue by KleiberW** [luconlua/sopra-cloud#94]
@wtuz @sg-sopraAG 
In der Kachel der Soprazonanlage sollten wir meiner Meinung nach den Text "Chlorbedarf" ändern in "Anlagenleistung" da sich für mich das so darstellt als ob der aktuell benötigte Chlorbedarf 6g/h ist. Es handelt sich aber um die eingestellte Anlagenleistung und nicht um einen Bedarf

**Comment by sg-sopraAG** [comment]
Ja das stimmt. Bitte ändern

**Comment by wtuz** [comment]
Änderung in der Datenpunktliste vom 18.08.2020 enthalten
