### ISSUE TITLE
Bedienungsanleitungen: Link auf unsere Webseite (versteckte Seite)

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#95]
@luconlua 
@Hendrik-Mueller 
ich habe hier einen Test Link, wo die aktuelle Bedienungsanleitung für die sopra pool control hinterlegt ist. Uns wurde gesagt, dass es so funktionieren müsste. Dort könnten wir dann für alle Bedienungsanleitungen erstellen und dort könnten wir diese auch selbst pflegen.

Nachricht von unserem Webentwickler:
das gesandte PDF ist nun via https://www.sopra.de/bedienungsanleitungen/pool-control-touch erreichbar.. 
Dieser Pfad redirected automatisch zum Dokument an sich: https://www.sopra.de/fileadmin/data/Bedienungsanleitungen/BA-Evoqua-sopra-pool-control%20touch-1.03-B-DE.pdf

**Comment by luconlua** [comment]
Haben das jetzt mal zu Testzwecken für die pool control umgestellt. Es funktioniert soweit. 
@sg-sopraAG: Wir benötigen die Links für alle Geräte und in den Sprachen EN,DE,NL,FR

Das Ganze funktioniert wie folgt: In der Datenpunktliste wird je Gerät eine Id eingetragen z.b: "pool_control_premium_manual_link". Diese ID dient als Übersetzungs-ID im Wörterbuch. Dort  wird letztendlich je Id und Sprache ein Download-Link eingetragen

**Comment by luconlua** [comment]
Kann getestet werden

**Comment by luconlua** [comment]
Bitte testen
