### ISSUE TITLE
Anmeldung auf die sopra cloud nicht möglich "Fehlermeldung"

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#96]
@luconlua @Hendrik-Mueller 
ich kann mich von meinem Homeoffice "laptop" momentan überhaupt nicht mehr anmelden
- Windows 10
- Firefox (neu) , da gab es heute ein Update
über google chrome geht es

**Comment by sg-sopraAG** [comment]
@luconlua @Hendrik-Mueller 
ach ja hier die Meldung:

![Screenshot_2020-08-06  ](https://user-images.githubusercontent.com/67409030/89548974-072dc700-d808-11ea-80af-cde19aadf5bf.png)

**Comment by Hendrik-Mueller** [comment]
Ich werde mir das Problem umgehend genauer anschauen.
Jedoch ist es bei so, dass ich mich nur mit Firefox anmelden kann.

**Comment by Hendrik-Mueller** [comment]
@sg-sopraAG 
Es gab Umstellungen bezüglich des Server-Workers. Bitte einmal in den Browsern den Cache löschen.
Danach sollte es wieder funktionieren.
