### ISSUE TITLE
Störmeldeanzeige - in der Anlagenleiste - Nullstellung?

### ISSUE THREAD

**Issue by sg-sopraAG** [luconlua/sopra-cloud#97]
@luconlua 
@KleiberW 
- wird der Fehlerzähler bei einer Fehlermeldung die wieder behoben wird, ob automatisch oder manuell, nicht automatisch wieder auf "0" gestellt.?
- wird eine "aktiv" Meldung auch in diesem Zähler gezählt und angezeigt? (hier ist es so, dass diese Meldung nicht in der Klocke angezeigt oder gezählt werden sollte, ist ja keine Fehlermeldung!
![Anmerkung 2020-08-10 095753_LI](https://user-images.githubusercontent.com/67409030/89762911-ad701a00-daf1-11ea-8d72-484f4e752ae7.jpg)

**Comment by sg-sopraAG** [comment]
@luconlua 
es müsste noch die Filtermöglichkeit bei den Störmeldungen geben  um ("alle" , "offene" oder "geschlossene") sich anzeigen zu lassen.

**Comment by luconlua** [comment]
Die Anzeige mit der Anzahl der Fehlermeldungen wurde nicht immer aktualisiert. Ist jetzt behoben.
Filtermöglichkeit wurde ergänzt
