### ISSUE TITLE
Symbole Betriebsartanzeige Sopra test werden nicht bei allen Testanlagen angezeigt

### ISSUE THREAD

**Issue by KleiberW** [luconlua/sopra-cloud#99]
Bei der Sopra Testanlage 2 werden die Betriebsartsymbole v. Sopratest bereits korrekt angezeigt, bei den anderen beiden Testanlagen noch nicht (Koblenz/Günzburg)
Gateway Software oder Datenpunkteliste update ?

**Comment by wtuz** [comment]
@luconlua 
Ist mir nicht ersichtlich weshalb das so ist... Werden die GW nicht alle gleichermaßen aktualisiert?

**Comment by luconlua** [comment]
Vermutung: es ist ein neuer Datenpunkt hinzugekommen. Nach einer Änderung an der Datenpunktliste (neue ergänzt,  vorhandene gelöscht) muss eine Migration in der Datenbank erfolgen. Die ist bisher nicht durchgeführt worden und wird noch nachgeholt. 
Workaround falls kurzfristige Lösung erforderlich: Gerät über Admin-Rolle löschen

**Comment by wtuz** [comment]
ok, hab die Evoqua Anlage gelöscht und neu hinzugefügt, jetzt passt es

**Comment by luconlua** [comment]
Funktioniert jetzt auch, ohne dass man die Anlage löschen muss

**Comment by wtuz** [comment]
Bei "sopra AG Testanlage 1" wird die Betriebsart beim sopra-test immer noch nicht angezeigt

**Comment by luconlua** [comment]
OK, bei Betriebsartanzeige muss man das Gerät bei "Alt"-Anlagen doch löschen (wird automatisch wieder hinzugefügt)

Parameter, die nach dem 31.07.2020 neu zur Datenpunktliste hinzukommen, werden automatisch mit Installation der neuen Datenpunktliste ergänzt.  Betriebsartanzeige wurde vor dem 31.07.2020  ergänzt
